config/routes.rb
Rails.application.routes.draw do
  resources :markets
  resources :comments, only: [:create, :destroy]
  resources :coins
  resources :bidings
  resources :players
  resources :posts
  resources :positions, only: [:create, :destroy]

  root 'home#index'
  post 'players/newc' => 'players#newc'

 devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }    
  
  get 'home/mypage' => 'home#mypage'
  get 'home/main'
  get 'home/show' => 'home#show'
  get 'home/mining' => 'home#mining'
  get 'home/make_wallet' => 'home#make_wallet'
  post 'home/tx' => 'home#tx'
  get 'home/view_tx' => 'home/view_tx'
  get 'home/view_all_wallet' => 'home#view_all_wallet'
  post 'home/spon_end' => 'home#spon_end'
  post 'coins/buy_coin' => 'coins#buy_coin'
  

end

app/models/player.rb
class Player < ApplicationRecord
    mount_uploader :image1, PlayerImgUploaderUploader
    mount_uploader :image2, PlayerImgUploaderUploader
    mount_uploader :image3, PlayerImgUploaderUploader
    mount_uploader :image4, PlayerImgUploaderUploader
    belongs_to :user
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    
    paginates_per 4
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
    @players = Player.order("created_at DESC").page params[:page]
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @posts = Post.where(:user_id => @player.user_id).order("created_at DESC").page params[:page]
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    
    @player = Player.new(player_params)
    # 선수 등록한 사람은 한 번만 가능하게
    @user = User.find(current_user.id) 
    @user.register = true
    @user.save
    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    @user = User.find(current_user.id) 
    @user.register = false
    @user.save
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    def newc
      @player = Player.find(params[:player_id])
      @comment = Comment.new
      @comment.content = params[:content]
      @comment.player_id = params[:player_id]
      @comment.email = params[:email]

      
      @comment.save
      @comments=Comment.all
      respond_to do |format|
          format.js
      end 
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :height, :weight, :team, :image1, :image2, :image3, :image4, :video, :user_id, :position)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
 
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>

  <div class="field">
    <%= f.label :team %>
    <%= f.text_field :team %>
  </div>

  <div class="field">
    <%= f.label :image1 %>
    <%= f.file_field :image1, accept: 'image/png.image/gif.image/jpeg' %>
  </div>

  <div class="field">
    <%= f.label :image2 %>
    <%= f.file_field :image2, accept: 'image/png.image/gif.image/jpeg' %>
  </div>

  <div class="field">
    <%= f.label :image3 %>
    <%= f.file_field :image3, accept: 'image/png.image/gif.image/jpeg' %>
  </div>

  <div class="field">
    <%= f.label :image4 %>
    <%= f.file_field :image4, accept: 'image/png.image/gif.image/jpeg' %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.text_field :video %>
  </div>
  
  <div class="field">
    <% arr = ['LWF','SS','CF','RWF','LWF','DMF','CMF','AMF','RMF','LB','CB','RB','GK'] %>
    <%= f.label :position %>
    <%= f.select :position, arr, {} %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_newc.html.erb
              <% player.comments.all.each do|comment|%>
                <% user = User.find(comment.email.to_i) %>
                <li>
                  <div class="comment_user_img">
                    <% if user.img.blank? %>
                      <%= image_tag("underdog1.png") %>
                    <% else %>
                      <%= image_tag(user.img) %>
                    <% end %>
                  </div>
                  <div class="comment_text">
                    <%= user.user_name%></br>
                    <%= comment.content%>
                  </div>
                  
                    <%#=link_to '댓글삭제', comment_path(comment), method: :delete, date: { confirm: 'Are you sure?'} %>
                  
                </li>
              <%end%>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<div class="container-fluid post_main_2">
  <div class="row post_sub">
    <section class="banner_section">
      <div class="wrapper">
        <div class="slogan">유망주의 후원금을 거래해보세요.</div>
        <div class="wrap">
           <div class="search">
              <input type="text" class="searchTerm" placeholder="Who are you looking for?">
              <button type="submit" class="searchButton">
                <i class="fa fa-search"></i>
             </button>
           </div>
        </div>
      </div>
    </section>
  </div>
  
  <div class="row">
    <section class="funding_section">
      <% if current_user.register == true %>
  <a  href="/players/new" onclick="alert('선수등록은 한 번만 할 수 있다!'); return false;">선수등록</a>
<%else%>
  <a  href="/players/new">선수 판매 등록하기</a>
<%end%>
    </section>
  </div>
  <div class="row ddd">
    <% @players.each do |player| %>
      <div class="col-sm-12 col-md-6 col-xl-3">
        <a href = "/players/<%= player.id %>">  
          <div class="card h-card">
            <div class="h-img-wrapper">
              <% if !player.image1.blank? %>
                <img class="card-img-top h-img" src="<%= player.image1 %>" alt="Card image cap">
              <% else %>
                <%= image_tag("placeholder_fest.jpeg", class: "card-img-top h-img") %>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="h-card-title"><%= player.name %></h5>
            </div>
          </div>
        </a>
      </div>
    <% end %>
    <div class="papa">
    <%= paginate @players %>
    </div>
  </div>
</div>




<style>

  .card{
    background-color: rgba(0,0,0,0.3);
  }
  .card-body{
    background: transparent;
    color: white;
    font-size: 1.6rem;
    padding-top: 2rem;
  }
  .card-body h5{
    text-align: center;
    color: white;
  }
  .ddd{
    width: 76%;
    margin: 0 auto;
  }
</style>

app/views/players/new.html.erb
<h1 style="margin-top: 10rem;">디자인 미완입니다. 양식에 맞춰 올려주세요</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>


<iframe width="560" height="315" src="https://www.youtube.com/embed/TNBOkPCvq0w" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

app/views/players/newc.js.erb
$("#comments").html("<%= escape_javascript(render partial: 'newc', locals: { player: @player } ) %>"); 

app/views/players/show.html.erb
<div class="player_detail_page">
  <div class="player_lnb_wrapper">
    <div class="player_profile">
      <div class="player_profile_img">
        <%= image_tag("#{@player.image1}") %>
      </div>
      <div class="player_name">
        <p class="kr_name">
          <span><%= image_tag("football.png") %></span><%= @player.name %><span><%= image_tag("football.png") %></span>
        </p>
        <p class="en_name">영어이름</p>
      </div>
    </div>
    <ul class="player_lnb">
      <li><a href="#player_detail_info" class="active">선수 정보</a></li>
      <li><a href="#player_support">후원 정보</a></li>
      <li><a href="#player_news">선수 소식</a></li>
    </ul>
  </div>
  <section id="player_detail_info">
    <h3>선수 정보</h3>
    <div class="detail_content">
      <div class="row">
        <div class="col-md-12">
          <div class="present_support_info">
            <p>다음 후원 시작가</br><span>12만 5천</span>원</p>
            <p>20% 지분 중 <span>1/5</span>사용 잔여 지분<span>16%</span></p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="wrapper detail_info">
            <h4>선수 기본 정보</h4>
            <ul>
              <li>
                <p>
                  <span>국적</span>
                  <span>대한민국</span>
                </p>
              </li>
              <li>
                <p>
              <span>소속팀</span>
              <span><%= @player.team %></span>
            </p>
              </li>
              <li>
                <p>
              <span>포지션</span>
              <span>LWF</span>
            </p>
              </li>
              <li>
                <p>
              <span>나이</span>
              <span>19</span>
            </p>
              </li>
              <li>
                <p>
              <span>주발</span>
              <span>오른발</span>
            </p>
              </li>
              <li>
                <p>
              <span>신장</span>
              <span><%= @player.height %></span>
            </p>
              </li>
              <li>
                <p>
              <span>체중</span>
              <span><%= @player.weight %></span>
            </p>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-8">
          <div class="wrapper player_position">
            <h4>선수 포지션</h4>
            <div class="row position_wrapper">
              <ul class="position_list col-md-6">
                <% pos_arr = ['LWF','SS','CF','RWF','LWF','DMF','CMF','AMF','RMF','LB','CB','RB','GK'] %>
                <% pos_arr.each_with_index do |pos,i|%>
                  <% if pos == @player.position %>
                    <li class='active'><%= pos %></li>
                  <% else %>
                    <li><%= pos %></li>
                  <% end %>
                  <% if i == 3 || i== 8 || i==11 %>
                  <br>
                  <%end%>
                <%end%>
                
              </ul>
              <div class="position_chart col-md-6">
                <canvas id="myChart"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="player_support">
    <h3>후원 정보</h3>
    <% if @posts.blank? %>
      <div class="detail_content">
        <div class="wrapper">
          아직 후원 내역이 없습니다.
        </div>
      </div>
    <% else %>
      <div class="detail_content">
      <div class="wrapper">
        <div class='row'>
        <% @posts.each do |post| %>
          <div class="col-sm-12 col-md-6 col-xl-3">
            <a href = "/posts/<%= post.id %>">  
              <div class="card h-card">
                <div class="h-img-wrapper">
                  <% if !post.image.blank? %>
                    <img class="card-img-top h-img" src="<%= post.image %>" alt="Card image cap">
                  <% else %>
                    <%= image_tag("placeholder_fest.jpeg", class: "card-img-top h-img") %>
                  <% end %>
                </div>
                <div class="card-body">
                  <h5 class="h-card-title" style="color:#09083a;"><%= post.title %></h5>
                </div>
              </div>
            </a>
          </div>
        <% end %>
      </div>
      </div>
    </div>
    <% end %>
    
    
  </section>
  <section id="player_news">
    <h3>선수 소식</h3>
    <div class="detail_content">
      <div class="row">
        <div class="col-md-8">
          <div class="wrapper player_video">
            <h4>하이라이트 영상</h4>
            <div class="rwd-video is-16x9">
              <iframe width="560" height="315" src="<%= @player.video%>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            </div>
            <div class="player_article">
              <ul>
                <li>
                  <a href="http://www.goal.com/kr/%EB%89%B4%EC%8A%A4/%EB%A9%94%EC%8B%9C-%EC%95%84%EC%A7%81-%EB%8C%80%ED%91%9C%ED%8C%80-%EC%9D%80%ED%87%B4-%EC%97%AC%EB%B6%80-%EA%B2%B0%EC%A0%95-%EC%95%88-%ED%96%88%EB%8B%A4/1opv7kl7rrzok1isxh9ym981ck" target="_black">
                    <div class="news_img_wrapper">
                      <%= image_tag("news_img.png") %>
                    </div>
                    <div class="news_content">
                      <h5>메시, 아직 대표팀 은퇴 여부 결정 안 했다</h5>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="http://www.goal.com/kr/%EB%89%B4%EC%8A%A4/%EB%A9%94%EC%8B%9C-%EC%95%84%EC%A7%81-%EB%8C%80%ED%91%9C%ED%8C%80-%EC%9D%80%ED%87%B4-%EC%97%AC%EB%B6%80-%EA%B2%B0%EC%A0%95-%EC%95%88-%ED%96%88%EB%8B%A4/1opv7kl7rrzok1isxh9ym981ck" target="_black">
                    <div class="news_img_wrapper">
                      <%= image_tag("news_img.png") %>
                    </div>
                    <div class="news_content">
                      <h5>메시, 아직 대표팀 은퇴 여부 결정 안 했다</h5>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="http://www.goal.com/kr/%EB%89%B4%EC%8A%A4/%EB%A9%94%EC%8B%9C-%EC%95%84%EC%A7%81-%EB%8C%80%ED%91%9C%ED%8C%80-%EC%9D%80%ED%87%B4-%EC%97%AC%EB%B6%80-%EA%B2%B0%EC%A0%95-%EC%95%88-%ED%96%88%EB%8B%A4/1opv7kl7rrzok1isxh9ym981ck" target="_black">
                    <div class="news_img_wrapper">
                      <%= image_tag("news_img.png") %>
                    </div>
                    <div class="news_content">
                      <h5>메시, 아직 대표팀 은퇴 여부 결정 안 했다</h5>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="http://www.goal.com/kr/%EB%89%B4%EC%8A%A4/%EB%A9%94%EC%8B%9C-%EC%95%84%EC%A7%81-%EB%8C%80%ED%91%9C%ED%8C%80-%EC%9D%80%ED%87%B4-%EC%97%AC%EB%B6%80-%EA%B2%B0%EC%A0%95-%EC%95%88-%ED%96%88%EB%8B%A4/1opv7kl7rrzok1isxh9ym981ck" target="_black">
                    <div class="news_img_wrapper">
                      <%= image_tag("news_img.png") %>
                    </div>
                    <div class="news_content">
                      <h5>메시, 아직 대표팀 은퇴 여부 결정 안 했다</h5>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="http://www.goal.com/kr/%EB%89%B4%EC%8A%A4/%EB%A9%94%EC%8B%9C-%EC%95%84%EC%A7%81-%EB%8C%80%ED%91%9C%ED%8C%80-%EC%9D%80%ED%87%B4-%EC%97%AC%EB%B6%80-%EA%B2%B0%EC%A0%95-%EC%95%88-%ED%96%88%EB%8B%A4/1opv7kl7rrzok1isxh9ym981ck" target="_black">
                    <div class="news_img_wrapper">
                      <%= image_tag("news_img.png") %>
                    </div>
                    <div class="news_content">
                      <h5>메시, 아직 대표팀 은퇴 여부 결정 안 했다</h5>
                    </div>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="wrapper cheer_comment">
            <h4>응원 한마디</h4>
            <ul id="comments">
              <% @player.comments.all.each do|comment|%>
                <% user = User.find(comment.email.to_i) %>
                <li>
                  <div class="comment_user_img">
                    <% if user.img.blank? %>
                      <%= image_tag("underdog1.png") %>
                    <% else %>
                      <%= image_tag(user.img) %>
                    <% end %>
                  </div>
                  <div class="comment_text">
                    <%= user.user_name%></br>
                    <%= comment.content%>
                  </div>
                  
                    <%#=link_to '댓글삭제', comment_path(comment), method: :delete, date: { confirm: 'Are you sure?'} %>
                </li>
              <%end%>
            </ul>
            <% c_usr = User.find(current_user.id) %>
            
            <%= form_tag('/players/newc', method: 'post',remote: true, authenticity_token: true) do %>
              <div class="comment_user_img">
                <%= image_tag(c_usr.img) %>
              </div>
              <div class="comment_input">
                <%= text_field_tag :content, nil, placeholder: "선수를 응원해보세요!" %>
              </div>
              
              <%= hidden_field_tag :player_id, @player.id %>
              <%= hidden_field_tag :email, current_user.id %>
              <div class="comment_btn">
                <%= submit_tag('등록')%>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </section>
  

</div>
    <%#= link_to 'Edit', edit_player_path(@player) %>
    <%#= link_to 'Back', players_path %>
    
<script>
  
  var ctx = document.getElementById('myChart').getContext('2d');
  var myRadarChart = new Chart(ctx, {
    type: 'radar',
    data: {
        labels: ['패스', '슈팅', '피지컬', '방어력', '스피드', '드리블'],
        datasets: [{
          label: "<%= @player.name %> 능력치",
          backgroundColor: 'rgba(255,81,47,0.5)',
          data: [50, 70, 40, 20, 80, 50]
        },
        {
          label: "선수 평균 능력치",
          backgroundColor: 'rgba(255,255,255,0.7)',
          data: [10, 50, 40, 90, 30, 30]
        }]
    },
    options: {
        scale: {
            // Hides the scale
            display: true,
            gridLines: {
              color: '#fff',
              lineWidth: 0.5
            },
            ticks: {
      beginAtZero: true,
      min: 0,
      max: 100,
      stepSize: 20
    },
        }
    }
  });
  
  function jp_active() {
    
  }
</script>