config/routes.rb
Rails.application.routes.draw do
  resources :markets
  resources :comments, only: [:create, :destroy]
  resources :coins
  resources :bidings
  resources :players
  resources :posts
  resources :positions, only: [:create, :destroy]

  root 'home#index'
  post 'players/newc' => 'players#newc'

 devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }    
  
  get 'home/mypage' => 'home#mypage'
  get 'home/main'
  get 'home/show' => 'home#show'
  get 'home/mining' => 'home#mining'
  get 'home/make_wallet' => 'home#make_wallet'
  post 'home/tx' => 'home#tx'
  get 'home/view_tx' => 'home/view_tx'
  get 'home/view_all_wallet' => 'home#view_all_wallet'
  post 'home/spon_end' => 'home#spon_end'
  post 'coins/buy_coin' => 'coins#buy_coin'
  

end

app/models/market.rb
class Market < ApplicationRecord
    belongs_to :user
    paginates_per 4
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /markets
  # GET /markets.json
  def index
    @markets = Market.all
    @markets = Market.order("created_at DESC").page params[:page]
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
    # 그 사람이 갖고 있는 전체코인
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to @market, notice: 'Market was successfully created.' }
        format.json { render :show, status: :created, location: @market }
      else
        format.html { render :new }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1
  # PATCH/PUT /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market.destroy
    respond_to do |format|
      format.html { redirect_to markets_url, notice: 'Market was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit(:price, :user_id, :name, :count, :rewards, :post_id, :title)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<p style='padding-top:10rem'></p>
<%= form_for(market) do |f| %>
  <% if market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% market.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <!--작성자-->
  <%= f.hidden_field :name, value: current_user.email %>
  
===자유시장 글쓰기===

  <!--자신이 갖고있는 코인의 post-->
  <% arr = [] %>
  <% @posts = Coin.where(:user_id => current_user.id) %>
  <% support_post = @posts.group(:post_id).count %>
  <% support_post.each do |k,v| %>
    <% arr.push(k) %>
  <%end%>
  <%= f.select :post_id, arr, {} %>
  
  <!--제목-->
  <div class="field">
    
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <!--개수-->
  <div class="field">
    
    <%= f.label :count %>
    <%= f.text_field :count %>
  </div>
  
  <!--rewards-->
  <div class="field">
    <%= f.label :rewards %>
    <%= f.text_field :rewards %>
  </div>
  
  <!--코인가격-->
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  
  <!--현재사용자 id값 받기-->
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %

app/views/markets/edit.html.erb
<h1>Editing Market</h1>

<%= render 'form', market: @market %>

<%= link_to 'Show', @market %> |
<%= link_to 'Back', markets_path %>

app/views/markets/index.html.erb
<div class="container-fluid post_main">
  <div class="row  post_sub">
    <section class="banner_section">
      <div class="wrapper">
        <div class="slogan">자신이 보유한 코인을 자유롭게 거래할 수 있습니다.</div>
        <div class="wrap">
           <div class="search">
              <input type="text" class="searchTerm" placeholder="Who are you looking for?">
              <button type="submit" class="searchButton">
                <i class="fa fa-search"></i>
             </button>
           </div>
        </div>
      </div>
    </section>
  </div>
  
  <div class="row">
    <section class="funding_section">
      <%= link_to '게시글 올리기', new_market_path %>
    </section>
  </div>
  
  
  
  <div class="row ddd">
    <% @markets.each do |market| %>
    <% m_post = Post.find(market.post_id) %>
      <div class="col-sm-12 col-md-6 col-xl-3">
        <a href = "/markets/<%= market.id %>">  
          <div class="card h-card">
            <div class="h-img-wrapper">
              <% if !m_post.image.blank? %>
                <img class="card-img-top h-img" src="<%= m_post.image %>" alt="Card image cap">
              <% else %>
                <%= image_tag("placeholder_fest.jpeg", class: "card-img-top h-img") %>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="h-card-title">임시 제목</h5>
              <!--<h5 class="h-card-title"><%#= market.name %></h5>-->
            </div>
          </div>
        </a>
      </div>
    <% end %>
    <div class="papa">
    <%= paginate @markets %>
    </div>
  </div>
</div>
<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th> 작성자 |</th> -->
<!--      <th> 판매코인&개수 |</th>-->
<!--      <th> 코인가격 |</th>-->
<!--      <th> 어떤코인(post) |</th>-->
<!--      <th> Rewards</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @markets.each do |market| %>-->
<!--      <tr>-->
<!--        <td><%= market.name %></td>-->
<!--        <td><%= market.count %></td>-->
<!--        <td><%= market.price %></td>-->
<!--        <td><%= market.post_id %></td>-->
<!--        <td><%= market.rewards %></td>-->
<!--        <td><%= link_to 'Show', market %></td>-->
<!--        <td><%= link_to 'Edit', edit_market_path(market) %></td>-->
<!--        <td><%= link_to 'Destroy', market, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<br>

<%= link_to 'New Market', new_market_path %>

app/views/markets/new.html.erb
<h1>New Market</h1>

<%= render 'form', market: @market %>

<%= link_to 'Back', markets_path %>

app/views/markets/show.html.erb
<p id="notice" style='padding-top:10rem'><%= notice %></p>

<p>
  <strong>가격:</strong>
  <%= @market.price %>
</p>

<p>
  <strong>사용자:</strong>
  <%= @market.user_id %>
</p>

<p>
  <strong>메일주소:</strong>
  <%= @market.name %>
</p>

<p>
  <strong>코인갯수:</strong>
  <%= @market.count %>
</p>

<p>
  <strong>어떤 포스트에 대한 건지:</strong>
  <%= @market.post_id %>
</p>


<hr>

<%# @coins = Coin.where(:user_id => @market.user_id) %>
<%# coin = @coins.group(@market.user_id).count %>
<%if current_user.id == @market.user_id %>
<%else%>
<form action='/coins/buy_coin' method='POST' onSubmit="jp_alert()">
  <input type='hidden' name='total_coin_num' value='<%= @market.count %>'></input>
  <input type='hidden' name='price' value='<%= @market.price %>'></input>
  <input type='hidden' name='id' value='<%= @market.id %>'></input>
  <input type='hidden' name='post_id' value='<%= @market.post_id %>'></input>
  <input type='hidden' name='ori_user_id' value='<%= @market.user_id %>'></input>
  <input type='hidden' name='new_user_id' value='<%= current_user.id %>'></input>
  코인구매갯수: <input type='text' name='count' id="count"></input>
  총 가격: 
  <input type='submit' value='구매'></input>
</form>
<%end%>



<%= link_to 'Edit', edit_market_path(@market) %> |
<%= link_to 'Back', markets_path %>


<script>
  function jp_alert() {
    var total_price = document.getElementById("count").value.to_i*<%= @market.price.to_i %>;
    <% cur_usr = User.find(current_user.id) %>
    if(<%= @market.count %> < document.getElementById("count").value ) {
      alert("구매할 수 있는 코인이 부족합니다.");
      return false;
      // 아래 수정요함 (안먹힘)
    }else if ( total_price > current_user.budget ) {
      alert("구매할 수 있는 돈이 없습니다.");
      return false;
    }else {
      return true;
    }
  }
</script>