config/routes.rb
Rails.application.routes.draw do
  resources :markets
  resources :comments, only: [:create, :destroy]
  resources :coins
  resources :bidings
  resources :players
  resources :posts
  resources :positions, only: [:create, :destroy]

  root 'home#index'
  post 'players/newc' => 'players#newc'

 devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }    
  
  get 'home/mypage' => 'home#mypage'
  get 'home/main'
  get 'home/show' => 'home#show'
  get 'home/mining' => 'home#mining'
  get 'home/make_wallet' => 'home#make_wallet'
  post 'home/tx' => 'home#tx'
  get 'home/view_tx' => 'home/view_tx'
  get 'home/view_all_wallet' => 'home#view_all_wallet'
  post 'home/spon_end' => 'home#spon_end'
  post 'coins/buy_coin' => 'coins#buy_coin'
  

end

app/models/biding.rb
class Biding < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/controllers/bidings_controller.rb
class BidingsController < ApplicationController
  before_action :set_biding, only: [:show, :edit, :update, :destroy]

  # GET /bidings
  # GET /bidings.json
  def index
    @bidings = Biding.all
  end

  # GET /bidings/1
  # GET /bidings/1.json
  def show
  end

  # GET /bidings/new
  def new
    @biding = Biding.new
  end

  # GET /bidings/1/edit
  def edit
  end

  # POST /bidings
  # POST /bidings.json
  def create
    n = params[:biding][:coin_count]
    for i in '1'..n
       @biding = Biding.new(biding_params)
       @biding.save
    end
    redirect_to :back

  end

  # PATCH/PUT /bidings/1
  # PATCH/PUT /bidings/1.json
  def update
    respond_to do |format|
      if @biding.update(biding_params)
        format.html { redirect_to @biding, notice: 'Biding was successfully updated.' }
        format.json { render :show, status: :ok, location: @biding }
      else
        format.html { render :edit }
        format.json { render json: @biding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bidings/1
  # DELETE /bidings/1.json
  def destroy
    @biding.destroy
    respond_to do |format|
      format.html { redirect_to bidings_url, notice: 'Biding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biding
      @biding = Biding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biding_params
      params.require(:biding).permit(:price, :success_bid, :post_id, :user_id, :coin_count)
    end
end

app/helpers/bidings_helper.rb
module BidingsHelper
end

app/views/bidings/edit.html.erb
<h1>Editing Biding</h1>

<%= render 'form', biding: @biding %>

<%= link_to 'Show', @biding %> |
<%= link_to 'Back', bidings_path %>

app/views/bidings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bidings</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Success bid</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bidings.each do |biding| %>
      <tr>
        <td><%= biding.price %></td>
        <td><%= biding.success_bid %></td>
        <td><%= biding.post_id %></td>
        <td><%= biding.user_id %></td>
        <td><%= link_to 'Show', biding %></td>
        <td><%= link_to 'Edit', edit_biding_path(biding) %></td>
        <td><%= link_to 'Destroy', biding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biding', new_biding_path %>

app/views/bidings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @biding.price %>
</p>

<p>
  <strong>Success bid:</strong>
  <%= @biding.success_bid %>
</p>

<p>
  <strong>Post:</strong>
  <%= @biding.post_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @biding.user_id %>
</p>

<%= link_to 'Edit', edit_biding_path(@biding) %> |
<%= link_to 'Back', bidings_path %>