config/routes.rb
Rails.application.routes.draw do
  resources :markets
  resources :comments, only: [:create, :destroy]
  resources :coins
  resources :bidings
  resources :players
  resources :posts
  resources :positions, only: [:create, :destroy]

  root 'home#index'
  post 'players/newc' => 'players#newc'

 devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }    
  
  get 'home/mypage' => 'home#mypage'
  get 'home/main'
  get 'home/show' => 'home#show'
  get 'home/mining' => 'home#mining'
  get 'home/make_wallet' => 'home#make_wallet'
  post 'home/tx' => 'home#tx'
  get 'home/view_tx' => 'home/view_tx'
  get 'home/view_all_wallet' => 'home#view_all_wallet'
  post 'home/spon_end' => 'home#spon_end'
  post 'coins/buy_coin' => 'coins#buy_coin'
  

end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token  
  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def buy_coin
    # 거래가 가능한지.
    if params[:total_coin_num].to_i < params[:count].to_i
      
    else
      # 잔고동기화
      seller = User.find(params[:ori_user_id])
      buyer = User.find(params[:new_user_id])
      seller.budget += params[:count].to_i * params[:price].to_i
      seller.save
      buyer.budget -= params[:count].to_i * params[:price].to_i
      buyer.save
      
      # 구매수량만큼 코인테이블에서 코인에 대한 소유자 바꿔주기
      @bidded_post = Coin.where(:post_id => params[:post_id], :user_id => params[:ori_user_id])
      count = 0
      for i in @bidded_post
        if(count < params[:count].to_i)
          i.user_id = params[:new_user_id]
          i.save
          count +=1
        else
          break
        end
      end
    
      # 마켓테이블에서 올린 전체coin갯수에서 팔린 코인 수 빼기.
      market_coin_count = Market.find(params[:id].to_i)
      market_coin_count.count -= params[:count].to_i
      market_coin_count.save
      
      redirect_to :back
    end
    
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:reward, :post_id, :user_id)
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_form.html.erb
<%= form_for(coin) do |f| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reward %>
    <%= f.number_field :reward %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.number_field :post_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coins</h1>

<table>
  <thead>
    <tr>
      <th>Reward</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.reward %></td>
        <td><%= coin.post_id %></td>
        <td><%= coin.user_id %></td>
        <td><%= link_to 'Show', coin %></td>
        <td><%= link_to 'Edit', edit_coin_path(coin) %></td>
        <td><%= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coin', new_coin_path %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reward:</strong>
  <%= @coin.reward %>
</p>

<p>
  <strong>Post:</strong>
  <%= @coin.post_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @coin.user_id %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>